### ISSUE TITLE
No go file

### ISSUE THREAD

**Issue by ifeanyilawrence** [Erwin011895/golang-rest-api#1]
Hey buddy,
Am interested in this repo, I need to work on a project using golang. I already have skills building api with other languages like C#, Node, however, I need to learn best practices and standard way of building goolang api with authentication.

**Comment by Erwin011895** [comment]
hi @ifeanyilawrence ,
Thank you for your concern. I will update this repo soon after my office hours. Around 23.00 GMT +07.00
